<a href="https://colab.research.google.com/github/dghiberdic/4cblw010-g9/blob/main/PET_FTIR_CNN_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices("GPU"))

TensorFlow version: 2.20.0
GPU available: []

In [2]:
from google.colab import files

uploaded = files.upload()

Saving y_labels.npy to y_labels.npy

In [3]:
from google.colab import files

uploaded = files.upload()

Saving X_spectra.npy to X_spectra.npy

In [4]:
import os

print(os.listdir())

['.config', 'X_spectra.npy', 'y_labels.npy', 'sample_data']

In [6]:
if X.ndim == 2:
    X = X[..., np.newaxis]

print("CNN input shape:", X.shape)

CNN input shape: (200, 3600, 1)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (160, 3600, 1)
X_test: (40, 3600, 1)
y_train: (160, 20)
y_test: (40, 20)

In [8]:
import tensorflow as tf
from tensorflow.keras import layers, models

def build_ftir_cnn(input_length, num_labels):
    model = models.Sequential([
        layers.Input(shape=(input_length, 1)),

        layers.Conv1D(32, kernel_size=7, activation="relu", padding="same"),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(64, kernel_size=5, activation="relu", padding="same"),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(128, kernel_size=3, activation="relu", padding="same"),
        layers.MaxPooling1D(pool_size=2),

        layers.GlobalAveragePooling1D(),

        layers.Dense(128, activation="relu"),
        layers.Dropout(0.3),

        layers.Dense(num_labels, activation="sigmoid")
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="binary_accuracy"),
            tf.keras.metrics.AUC(name="auc")
        ]
    )

    return model


input_length = X_train.shape[1]
num_labels = y_train.shape[1]

model = build_ftir_cnn(input_length, num_labels)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 3600, 32)       │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 1800, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 1800, 64)       │        10,304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 900, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 900, 128)       │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 450, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 20)             │         2,580 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54,356 (212.33 KB)

 Trainable params: 54,356 (212.33 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=8,
        restore_best_weights=True
    )
]

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=16,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 219ms/step - auc: 0.5065 - binary_accuracy: 0.5023 - loss: 0.6930 - val_auc: 0.4653 - val_binary_accuracy: 0.4781 - val_loss: 0.6958
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 168ms/step - auc: 0.5404 - binary_accuracy: 0.5234 - loss: 0.6908 - val_auc: 0.4687 - val_binary_accuracy: 0.4844 - val_loss: 0.6977
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 169ms/step - auc: 0.5526 - binary_accuracy: 0.5398 - loss: 0.6891 - val_auc: 0.4714 - val_binary_accuracy: 0.4844 - val_loss: 0.7008
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 169ms/step - auc: 0.5471 - binary_accuracy: 0.5285 - loss: 0.6894 - val_auc: 0.4687 - val_binary_accuracy: 0.4906 - val_loss: 0.7024
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 165ms/step - auc: 0.5562 - binary_accuracy: 0.5379 - loss: 0.6881 - val_auc: 0.4730 - val_binary_accuracy: 0.4844 - val_loss: 0.7034
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 174ms/step - auc: 0.5522 - binary_accuracy: 0.5383 - loss: 0.6885 - val_auc: 0.4728 - val_binary_accuracy: 0.4906 - val_loss: 0.7027
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 218ms/step - auc: 0.5551 - binary_accuracy: 0.5426 - loss: 0.6888 - val_auc: 0.4757 - val_binary_accuracy: 0.5000 - val_loss: 0.7015
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 196ms/step - auc: 0.5510 - binary_accuracy: 0.5340 - loss: 0.6889 - val_auc: 0.4752 - val_binary_accuracy: 0.4937 - val_loss: 0.7001
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 170ms/step - auc: 0.5543 - binary_accuracy: 0.5320 - loss: 0.6882 - val_auc: 0.4777 - val_binary_accuracy: 0.4937 - val_loss: 0.7013

In [10]:
from sklearn.metrics import f1_score, classification_report

LABEL_NAMES = [
    "ester",
    "carboxylic_acid",
    "alkane",
    "alkene",
    "alcohol",
    "arene",
    "amine",
    "ketone",
    "ether",
    "imine",
    "sulfonamide",
    "acyl_halide",
    "phosphate",
    "aldehyde",
    "nitro",
    "enamine",
    "azo",
    "sulfonic_acid",
    "amide",
    "peroxide",
]

y_prob = model.predict(X_test)
y_pred = (y_prob >= 0.5).astype(int)

micro_f1 = f1_score(y_test, y_pred, average="micro", zero_division=0)
macro_f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)
samples_f1 = f1_score(y_test, y_pred, average="samples", zero_division=0)

print("CNN Evaluation")
print("Micro F1:", micro_f1)
print("Macro F1:", macro_f1)
print("Samples F1:", samples_f1)

print(classification_report(
    y_test,
    y_pred,
    target_names=LABEL_NAMES,
    zero_division=0
))

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 455ms/step
CNN Evaluation
Micro F1: 0.4196185286103542
Macro F1: 0.25858320243230026
Samples F1: 0.4105226904401591
                 precision    recall  f1-score   support

          ester       0.00      0.00      0.00        22
carboxylic_acid       0.40      1.00      0.57        16
         alkane       0.47      1.00      0.64        19
         alkene       0.47      1.00      0.64        19
        alcohol       0.00      0.00      0.00        19
          arene       0.00      0.00      0.00        24
          amine       0.00      0.00      0.00        23
         ketone       0.55      1.00      0.71        22
          ether       0.00      0.00      0.00        25
          imine       0.55      1.00      0.71        22
    sulfonamide       0.00      0.00      0.00        21
    acyl_halide       0.57      1.00      0.73        23
      phosphate       0.00      0.00      0.00        23
       aldehyde       0.00      0.00      0.00        20
          nitro       0.47      1.00      0.64        19
        enamine       0.00      0.00      0.00        20
            azo       0.00      0.00      0.00        15
  sulfonic_acid       0.00      0.00      0.00        27
          amide       0.35      1.00      0.52        14
       peroxide       0.00      0.00      0.00        21

      micro avg       0.48      0.37      0.42       414
      macro avg       0.19      0.40      0.26       414
   weighted avg       0.18      0.37      0.24       414
    samples avg       0.48      0.37      0.41       414

In [1]:
from google.colab import files

uploaded = files.upload()

Saving X_spectra.npy to X_spectra.npy
Saving y_labels.npy to y_labels.npy

In [2]:
import numpy as np
import os

print(os.listdir())

X = np.load("X_spectra.npy")
y = np.load("y_labels.npy")

print("X shape:", X.shape)
print("y shape:", y.shape)
print("X min:", X.min())
print("X max:", X.max())
print("y unique:", np.unique(y))

['.config', 'X_spectra.npy', 'y_labels.npy', 'sample_data']
X shape: (13253, 1800)
y shape: (13253, 20)
X min: nan
X max: nan
y unique: [0 1]

In [3]:
import numpy as np

print("Total NaNs in X:", np.isnan(X).sum())
print("Rows with at least one NaN:", np.isnan(X).any(axis=1).sum())

Total NaNs in X: 52200
Rows with at least one NaN: 29

In [4]:
valid_rows = ~np.isnan(X).any(axis=1)

X_clean = X[valid_rows]
y_clean = y[valid_rows]

print("Original X:", X.shape)
print("Clean X:", X_clean.shape)
print("Original y:", y.shape)
print("Clean y:", y_clean.shape)

print("NaNs after cleaning:", np.isnan(X_clean).sum())
print("X clean min:", np.min(X_clean))
print("X clean max:", np.max(X_clean))

Original X: (13253, 1800)
Clean X: (13224, 1800)
Original y: (13253, 20)
Clean y: (13224, 20)
NaNs after cleaning: 0
X clean min: 0.0
X clean max: 1.0

In [5]:
import numpy as np

X = np.load("X_spectra.npy")
y = np.load("y_labels.npy")

print("X shape:", X.shape)
print("y shape:", y.shape)
print("X min:", X.min())
print("X max:", X.max())
print("y unique values:", np.unique(y))

X shape: (200, 3600)
y shape: (200, 20)
X min: 4.167095124074649e-06
X max: 0.9999998314950046
y unique values: [0 1]

In [5]:
X = X_clean
y = y_clean

if X.ndim == 2:
    X = X[..., np.newaxis]

print("CNN input shape:", X.shape)
print("y shape:", y.shape)

CNN input shape: (13224, 1800, 1)
y shape: (13224, 20)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (10579, 1800, 1)
X_test: (2645, 1800, 1)
y_train: (10579, 20)
y_test: (2645, 20)

In [7]:
import tensorflow as tf
from tensorflow.keras import layers, models

LABEL_NAMES = [
    "ester",
    "carboxylic_acid",
    "alkane",
    "alkene",
    "alcohol",
    "arene",
    "amine",
    "ketone",
    "ether",
    "imine",
    "sulfonamide",
    "acyl_halide",
    "phosphate",
    "aldehyde",
    "nitro",
    "enamine",
    "azo",
    "sulfonic_acid",
    "amide",
    "peroxide",
]

def build_ftir_cnn(input_length, num_labels):
    model = models.Sequential([
        layers.Input(shape=(input_length, 1)),

        layers.Conv1D(32, kernel_size=7, activation="relu", padding="same"),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(64, kernel_size=5, activation="relu", padding="same"),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(128, kernel_size=3, activation="relu", padding="same"),
        layers.MaxPooling1D(pool_size=2),

        layers.GlobalAveragePooling1D(),

        layers.Dense(128, activation="relu"),
        layers.Dropout(0.3),

        layers.Dense(num_labels, activation="sigmoid")
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="binary_accuracy"),
            tf.keras.metrics.AUC(name="auc")
        ]
    )

    return model

input_length = X_train.shape[1]
num_labels = y_train.shape[1]

model = build_ftir_cnn(input_length, num_labels)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 1800, 32)       │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 900, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 900, 64)        │        10,304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 450, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_2 (Conv1D)               │ (None, 450, 128)       │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_2 (MaxPooling1D)  │ (None, 225, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 20)             │         2,580 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54,356 (212.33 KB)

 Trainable params: 54,356 (212.33 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=6,
        restore_best_weights=True
    )
]

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=40,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 55s 185ms/step - auc: 0.8519 - binary_accuracy: 0.8882 - loss: 0.3062 - val_auc: 0.8922 - val_binary_accuracy: 0.8975 - val_loss: 0.2591
Epoch 2/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 51s 193ms/step - auc: 0.8883 - binary_accuracy: 0.8977 - loss: 0.2646 - val_auc: 0.8945 - val_binary_accuracy: 0.8978 - val_loss: 0.2567
Epoch 3/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 49s 186ms/step - auc: 0.8916 - binary_accuracy: 0.8979 - loss: 0.2607 - val_auc: 0.8961 - val_binary_accuracy: 0.8979 - val_loss: 0.2544
Epoch 4/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 183ms/step - auc: 0.8938 - binary_accuracy: 0.8983 - loss: 0.2579 - val_auc: 0.8966 - val_binary_accuracy: 0.8978 - val_loss: 0.2550
Epoch 5/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 50s 188ms/step - auc: 0.8945 - binary_accuracy: 0.8986 - loss: 0.2569 - val_auc: 0.8979 - val_binary_accuracy: 0.8978 - val_loss: 0.2528
Epoch 6/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 81s 183ms/step - auc: 0.8957 - binary_accuracy: 0.8985 - loss: 0.2556 - val_auc: 0.8979 - val_binary_accuracy: 0.8995 - val_loss: 0.2533
Epoch 7/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 80s 177ms/step - auc: 0.8959 - binary_accuracy: 0.8988 - loss: 0.2552 - val_auc: 0.8980 - val_binary_accuracy: 0.8976 - val_loss: 0.2529
Epoch 8/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 83s 182ms/step - auc: 0.8963 - binary_accuracy: 0.8991 - loss: 0.2547 - val_auc: 0.8988 - val_binary_accuracy: 0.8989 - val_loss: 0.2525
Epoch 9/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 47s 178ms/step - auc: 0.8965 - binary_accuracy: 0.8990 - loss: 0.2545 - val_auc: 0.8994 - val_binary_accuracy: 0.8991 - val_loss: 0.2512
Epoch 10/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 49s 186ms/step - auc: 0.8970 - binary_accuracy: 0.8992 - loss: 0.2541 - val_auc: 0.9000 - val_binary_accuracy: 0.8991 - val_loss: 0.2510
Epoch 11/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 81s 182ms/step - auc: 0.8976 - binary_accuracy: 0.8990 - loss: 0.2536 - val_auc: 0.9006 - val_binary_accuracy: 0.8992 - val_loss: 0.2504
Epoch 12/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 47s 176ms/step - auc: 0.8980 - binary_accuracy: 0.8990 - loss: 0.2534 - val_auc: 0.9006 - val_binary_accuracy: 0.8999 - val_loss: 0.2503
Epoch 13/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 182ms/step - auc: 0.8989 - binary_accuracy: 0.8996 - loss: 0.2525 - val_auc: 0.9005 - val_binary_accuracy: 0.8978 - val_loss: 0.2511
Epoch 14/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 81s 177ms/step - auc: 0.8994 - binary_accuracy: 0.8993 - loss: 0.2521 - val_auc: 0.9018 - val_binary_accuracy: 0.9006 - val_loss: 0.2496
Epoch 15/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 183ms/step - auc: 0.8999 - binary_accuracy: 0.8996 - loss: 0.2515 - val_auc: 0.9017 - val_binary_accuracy: 0.8989 - val_loss: 0.2497
Epoch 16/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 47s 176ms/step - auc: 0.9004 - binary_accuracy: 0.8999 - loss: 0.2511 - val_auc: 0.9016 - val_binary_accuracy: 0.8997 - val_loss: 0.2491
Epoch 17/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 50s 189ms/step - auc: 0.9012 - binary_accuracy: 0.9004 - loss: 0.2505 - val_auc: 0.9024 - val_binary_accuracy: 0.9000 - val_loss: 0.2486
Epoch 18/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 47s 176ms/step - auc: 0.9014 - binary_accuracy: 0.8998 - loss: 0.2502 - val_auc: 0.9032 - val_binary_accuracy: 0.9008 - val_loss: 0.2480
Epoch 19/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 51s 191ms/step - auc: 0.9016 - binary_accuracy: 0.9005 - loss: 0.2499 - val_auc: 0.9038 - val_binary_accuracy: 0.9003 - val_loss: 0.2472
Epoch 20/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 78s 176ms/step - auc: 0.9016 - binary_accuracy: 0.9005 - loss: 0.2499 - val_auc: 0.9021 - val_binary_accuracy: 0.8996 - val_loss: 0.2496
Epoch 21/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 181ms/step - auc: 0.9020 - binary_accuracy: 0.9006 - loss: 0.2492 - val_auc: 0.9040 - val_binary_accuracy: 0.9006 - val_loss: 0.2472
Epoch 22/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 46s 175ms/step - auc: 0.9021 - binary_accuracy: 0.9006 - loss: 0.2492 - val_auc: 0.9034 - val_binary_accuracy: 0.9003 - val_loss: 0.2486
Epoch 23/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 84s 183ms/step - auc: 0.9024 - binary_accuracy: 0.9004 - loss: 0.2488 - val_auc: 0.9043 - val_binary_accuracy: 0.9009 - val_loss: 0.2466
Epoch 24/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 82s 182ms/step - auc: 0.9032 - binary_accuracy: 0.9011 - loss: 0.2481 - val_auc: 0.9050 - val_binary_accuracy: 0.9013 - val_loss: 0.2460
Epoch 25/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 49s 185ms/step - auc: 0.9035 - binary_accuracy: 0.9013 - loss: 0.2476 - val_auc: 0.9046 - val_binary_accuracy: 0.9007 - val_loss: 0.2463
Epoch 26/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 83s 190ms/step - auc: 0.9039 - binary_accuracy: 0.9009 - loss: 0.2475 - val_auc: 0.9054 - val_binary_accuracy: 0.9016 - val_loss: 0.2452
Epoch 27/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 181ms/step - auc: 0.9043 - binary_accuracy: 0.9010 - loss: 0.2469 - val_auc: 0.9055 - val_binary_accuracy: 0.9015 - val_loss: 0.2450
Epoch 28/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 84s 190ms/step - auc: 0.9045 - binary_accuracy: 0.9013 - loss: 0.2467 - val_auc: 0.9063 - val_binary_accuracy: 0.9015 - val_loss: 0.2444
Epoch 29/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 81s 185ms/step - auc: 0.9046 - binary_accuracy: 0.9013 - loss: 0.2465 - val_auc: 0.9061 - val_binary_accuracy: 0.9021 - val_loss: 0.2443
Epoch 30/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 182ms/step - auc: 0.9053 - binary_accuracy: 0.9015 - loss: 0.2459 - val_auc: 0.9065 - val_binary_accuracy: 0.9015 - val_loss: 0.2437
Epoch 31/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 47s 176ms/step - auc: 0.9052 - binary_accuracy: 0.9017 - loss: 0.2457 - val_auc: 0.9064 - val_binary_accuracy: 0.9022 - val_loss: 0.2440
Epoch 32/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 86s 192ms/step - auc: 0.9053 - binary_accuracy: 0.9022 - loss: 0.2455 - val_auc: 0.9074 - val_binary_accuracy: 0.9029 - val_loss: 0.2430
Epoch 33/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 78s 177ms/step - auc: 0.9057 - binary_accuracy: 0.9021 - loss: 0.2451 - val_auc: 0.9071 - val_binary_accuracy: 0.9026 - val_loss: 0.2432
Epoch 34/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 84s 186ms/step - auc: 0.9062 - binary_accuracy: 0.9024 - loss: 0.2447 - val_auc: 0.9080 - val_binary_accuracy: 0.9024 - val_loss: 0.2436
Epoch 35/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 47s 176ms/step - auc: 0.9061 - binary_accuracy: 0.9027 - loss: 0.2447 - val_auc: 0.9069 - val_binary_accuracy: 0.9022 - val_loss: 0.2429
Epoch 36/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 49s 186ms/step - auc: 0.9067 - binary_accuracy: 0.9029 - loss: 0.2440 - val_auc: 0.9079 - val_binary_accuracy: 0.9040 - val_loss: 0.2421
Epoch 37/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 49s 187ms/step - auc: 0.9068 - binary_accuracy: 0.9030 - loss: 0.2437 - val_auc: 0.9089 - val_binary_accuracy: 0.9041 - val_loss: 0.2408
Epoch 38/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 48s 181ms/step - auc: 0.9073 - binary_accuracy: 0.9031 - loss: 0.2431 - val_auc: 0.9092 - val_binary_accuracy: 0.9024 - val_loss: 0.2413
Epoch 39/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 49s 186ms/step - auc: 0.9076 - binary_accuracy: 0.9038 - loss: 0.2427 - val_auc: 0.9088 - val_binary_accuracy: 0.9030 - val_loss: 0.2412
Epoch 40/40
265/265 ━━━━━━━━━━━━━━━━━━━━ 81s 182ms/step - auc: 0.9082 - binary_accuracy: 0.9038 - loss: 0.2421 - val_auc: 0.9095 - val_binary_accuracy: 0.9047 - val_loss: 0.2400

In [9]:
from sklearn.metrics import f1_score, classification_report

LABEL_NAMES = [
    "ester",
    "carboxylic_acid",
    "alkane",
    "alkene",
    "alcohol",
    "arene",
    "amine",
    "ketone",
    "ether",
    "imine",
    "sulfonamide",
    "acyl_halide",
    "phosphate",
    "aldehyde",
    "nitro",
    "enamine",
    "azo",
    "sulfonic_acid",
    "amide",
    "peroxide",
]

y_prob = model.predict(X_test)
y_pred = (y_prob >= 0.5).astype(int)

micro_f1 = f1_score(y_test, y_pred, average="micro", zero_division=0)
macro_f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)
samples_f1 = f1_score(y_test, y_pred, average="samples", zero_division=0)

print("CNN Evaluation")
print("Micro F1:", micro_f1)
print("Macro F1:", macro_f1)
print("Samples F1:", samples_f1)

print(classification_report(
    y_test,
    y_pred,
    target_names=LABEL_NAMES,
    zero_division=0
))

83/83 ━━━━━━━━━━━━━━━━━━━━ 5s 62ms/step
CNN Evaluation
Micro F1: 0.5796361840480698
Macro F1: 0.09207832273653282
Samples F1: 0.5740835849720538
                 precision    recall  f1-score   support

          ester       0.00      0.00      0.00       412
carboxylic_acid       0.00      0.00      0.00       132
         alkane       0.81      0.99      0.89      2121
         alkene       0.00      0.00      0.00       375
        alcohol       0.00      0.00      0.00       667
          arene       0.79      0.81      0.80      1670
          amine       0.00      0.00      0.00       798
         ketone       0.00      0.00      0.00       260
          ether       0.70      0.09      0.15       749
          imine       0.00      0.00      0.00        35
    sulfonamide       0.00      0.00      0.00        41
    acyl_halide       0.00      0.00      0.00        11
      phosphate       0.00      0.00      0.00        49
       aldehyde       0.00      0.00      0.00        56
          nitro       0.00      0.00      0.00       158
        enamine       0.00      0.00      0.00         5
            azo       0.00      0.00      0.00        27
  sulfonic_acid       0.00      0.00      0.00        20
          amide       0.00      0.00      0.00       148
       peroxide       0.00      0.00      0.00         3

      micro avg       0.80      0.46      0.58      7737
      macro avg       0.11      0.09      0.09      7737
   weighted avg       0.46      0.46      0.43      7737
    samples avg       0.80      0.49      0.57      7737

In [10]:
import numpy as np
from sklearn.metrics import f1_score

thresholds = np.arange(0.1, 0.91, 0.05)

rows = []

for t in thresholds:
    y_pred_t = (y_prob >= t).astype(int)
    rows.append({
        "threshold": t,
        "micro_f1": f1_score(y_test, y_pred_t, average="micro", zero_division=0),
        "macro_f1": f1_score(y_test, y_pred_t, average="macro", zero_division=0),
        "samples_f1": f1_score(y_test, y_pred_t, average="samples", zero_division=0),
    })

import pandas as pd

threshold_df = pd.DataFrame(rows)
threshold_df

    threshold  micro_f1  macro_f1  samples_f1
0        0.10  0.545842  0.216224    0.529084
1        0.15  0.591683  0.208400    0.572771
2        0.20  0.609467  0.195849    0.594510
3        0.25  0.626253  0.184187    0.612653
4        0.30  0.630051  0.171848    0.617080
5        0.35  0.621685  0.152498    0.608808
6        0.40  0.600031  0.112221    0.591214
7        0.45  0.589533  0.097467    0.583272
8        0.50  0.579636  0.092078    0.574084
9        0.55  0.565027  0.088262    0.560816
10       0.60  0.549432  0.084233    0.546658
11       0.65  0.530310  0.080407    0.528423
12       0.70  0.503725  0.075964    0.497879
13       0.75  0.433000  0.068994    0.403030
14       0.80  0.306684  0.053563    0.250413
15       0.85  0.222552  0.040939    0.170615
16       0.90  0.152601  0.029322    0.116403

In [11]:
threshold_df.sort_values("macro_f1", ascending=False).head(10)

   threshold  micro_f1  macro_f1  samples_f1
0       0.10  0.545842  0.216224    0.529084
1       0.15  0.591683  0.208400    0.572771
2       0.20  0.609467  0.195849    0.594510
3       0.25  0.626253  0.184187    0.612653
4       0.30  0.630051  0.171848    0.617080
5       0.35  0.621685  0.152498    0.608808
6       0.40  0.600031  0.112221    0.591214
7       0.45  0.589533  0.097467    0.583272
8       0.50  0.579636  0.092078    0.574084
9       0.55  0.565027  0.088262    0.560816

In [12]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report

LABEL_NAMES = [
    "ester", "carboxylic_acid", "alkane", "alkene", "alcohol",
    "arene", "amine", "ketone", "ether", "imine",
    "sulfonamide", "acyl_halide", "phosphate", "aldehyde", "nitro",
    "enamine", "azo", "sulfonic_acid", "amide", "peroxide"
]

# Train/test split again
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

# Calculate class weights per label
positive_counts = y_train.sum(axis=0)
negative_counts = len(y_train) - positive_counts

# Avoid division by zero
pos_weights = negative_counts / np.maximum(positive_counts, 1)

# Clip weights so rare labels do not explode too much
pos_weights = np.clip(pos_weights, 1.0, 20.0)

print("Positive class weights:")
for name, weight, count in zip(LABEL_NAMES, pos_weights, positive_counts):
    print(f"{name}: weight={weight:.2f}, positives={int(count)}")


def weighted_binary_crossentropy(pos_weights):
    pos_weights_tf = tf.constant(pos_weights, dtype=tf.float32)

    def loss_fn(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)

        # Prevent log(0)
        epsilon = tf.keras.backend.epsilon()
        y_pred = tf.clip_by_value(y_pred, epsilon, 1.0 - epsilon)

        loss_pos = -y_true * tf.math.log(y_pred) * pos_weights_tf
        loss_neg = -(1.0 - y_true) * tf.math.log(1.0 - y_pred)

        return tf.reduce_mean(loss_pos + loss_neg)

    return loss_fn

X_train: (10579, 1800, 1)
X_test: (2645, 1800, 1)
y_train: (10579, 20)
y_test: (2645, 20)
Positive class weights:
ester: weight=6.13, positives=1484
carboxylic_acid: weight=18.52, positives=542
alkane: weight=1.00, positives=8424
alkene: weight=6.02, positives=1507
alcohol: weight=3.03, positives=2625
arene: weight=1.00, positives=6562
amine: weight=2.40, positives=3107
ketone: weight=9.53, positives=1005
ether: weight=2.61, positives=2927
imine: weight=20.00, positives=114
sulfonamide: weight=20.00, positives=115
acyl_halide: weight=20.00, positives=34
phosphate: weight=20.00, positives=187
aldehyde: weight=20.00, positives=245
nitro: weight=17.99, positives=557
enamine: weight=20.00, positives=47
azo: weight=20.00, positives=104
sulfonic_acid: weight=20.00, positives=120
amide: weight=14.65, positives=676
peroxide: weight=20.00, positives=12

In [13]:
def build_better_ftir_cnn(input_length, num_labels, pos_weights):
    model = models.Sequential([
        layers.Input(shape=(input_length, 1)),

        layers.Conv1D(32, kernel_size=9, activation="relu", padding="same"),
        layers.BatchNormalization(),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(64, kernel_size=7, activation="relu", padding="same"),
        layers.BatchNormalization(),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(128, kernel_size=5, activation="relu", padding="same"),
        layers.BatchNormalization(),
        layers.MaxPooling1D(pool_size=2),

        layers.Conv1D(128, kernel_size=3, activation="relu", padding="same"),
        layers.BatchNormalization(),

        layers.GlobalAveragePooling1D(),

        layers.Dense(128, activation="relu"),
        layers.Dropout(0.4),

        layers.Dense(num_labels, activation="sigmoid")
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=5e-4),
        loss=weighted_binary_crossentropy(pos_weights),
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="binary_accuracy"),
            tf.keras.metrics.AUC(name="auc")
        ]
    )

    return model


input_length = X_train.shape[1]
num_labels = y_train.shape[1]

model = build_better_ftir_cnn(input_length, num_labels, pos_weights)
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_3 (Conv1D)               │ (None, 1800, 32)       │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 1800, 32)       │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_3 (MaxPooling1D)  │ (None, 900, 32)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_4 (Conv1D)               │ (None, 900, 64)        │        14,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 900, 64)        │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_4 (MaxPooling1D)  │ (None, 450, 64)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_5 (Conv1D)               │ (None, 450, 128)       │        41,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 450, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_5 (MaxPooling1D)  │ (None, 225, 128)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_6 (Conv1D)               │ (None, 225, 128)       │        49,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 225, 128)       │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling1d_1      │ (None, 128)            │             0 │
│ (GlobalAveragePooling1D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 20)             │         2,580 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 125,588 (490.58 KB)

 Trainable params: 124,884 (487.83 KB)

 Non-trainable params: 704 (2.75 KB)

In [14]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=8,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-5
    )
]

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 107s 378ms/step - auc: 0.8004 - binary_accuracy: 0.7307 - loss: 0.8519 - val_auc: 0.8155 - val_binary_accuracy: 0.7785 - val_loss: 0.8403 - learning_rate: 5.0000e-04
Epoch 2/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 103s 390ms/step - auc: 0.8359 - binary_accuracy: 0.7559 - loss: 0.8168 - val_auc: 0.8398 - val_binary_accuracy: 0.7908 - val_loss: 0.8084 - learning_rate: 5.0000e-04
Epoch 3/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 138s 373ms/step - auc: 0.8450 - binary_accuracy: 0.7619 - loss: 0.8013 - val_auc: 0.8686 - val_binary_accuracy: 0.8093 - val_loss: 0.7876 - learning_rate: 5.0000e-04
Epoch 4/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 140s 367ms/step - auc: 0.8457 - binary_accuracy: 0.7621 - loss: 0.7933 - val_auc: 0.8568 - val_binary_accuracy: 0.7509 - val_loss: 0.8069 - learning_rate: 5.0000e-04
Epoch 5/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 371ms/step - auc: 0.8500 - binary_accuracy: 0.7679 - loss: 0.7874 - val_auc: 0.8590 - val_binary_accuracy: 0.7910 - val_loss: 0.8007 - learning_rate: 5.0000e-04
Epoch 6/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 141s 369ms/step - auc: 0.8551 - binary_accuracy: 0.7742 - loss: 0.7782 - val_auc: 0.8557 - val_binary_accuracy: 0.7821 - val_loss: 0.7799 - learning_rate: 5.0000e-04
Epoch 7/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 103s 390ms/step - auc: 0.8547 - binary_accuracy: 0.7738 - loss: 0.7772 - val_auc: 0.8658 - val_binary_accuracy: 0.7969 - val_loss: 0.7776 - learning_rate: 5.0000e-04
Epoch 8/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 96s 362ms/step - auc: 0.8577 - binary_accuracy: 0.7728 - loss: 0.7712 - val_auc: 0.8472 - val_binary_accuracy: 0.7146 - val_loss: 0.7967 - learning_rate: 5.0000e-04
Epoch 9/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 144s 370ms/step - auc: 0.8605 - binary_accuracy: 0.7793 - loss: 0.7662 - val_auc: 0.8517 - val_binary_accuracy: 0.7869 - val_loss: 0.7925 - learning_rate: 5.0000e-04
Epoch 10/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 96s 363ms/step - auc: 0.8600 - binary_accuracy: 0.7771 - loss: 0.7657 - val_auc: 0.8600 - val_binary_accuracy: 0.7730 - val_loss: 0.7769 - learning_rate: 5.0000e-04
Epoch 11/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 97s 366ms/step - auc: 0.8632 - binary_accuracy: 0.7804 - loss: 0.7578 - val_auc: 0.8709 - val_binary_accuracy: 0.7923 - val_loss: 0.7556 - learning_rate: 5.0000e-04
Epoch 12/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 146s 381ms/step - auc: 0.8628 - binary_accuracy: 0.7809 - loss: 0.7553 - val_auc: 0.8784 - val_binary_accuracy: 0.7889 - val_loss: 0.7632 - learning_rate: 5.0000e-04
Epoch 13/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 100s 379ms/step - auc: 0.8663 - binary_accuracy: 0.7795 - loss: 0.7519 - val_auc: 0.8635 - val_binary_accuracy: 0.7887 - val_loss: 0.7600 - learning_rate: 5.0000e-04
Epoch 14/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 100s 378ms/step - auc: 0.8686 - binary_accuracy: 0.7820 - loss: 0.7490 - val_auc: 0.8701 - val_binary_accuracy: 0.7616 - val_loss: 0.7593 - learning_rate: 5.0000e-04
Epoch 15/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 140s 370ms/step - auc: 0.8725 - binary_accuracy: 0.7873 - loss: 0.7385 - val_auc: 0.8735 - val_binary_accuracy: 0.7946 - val_loss: 0.7426 - learning_rate: 2.5000e-04
Epoch 16/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 370ms/step - auc: 0.8732 - binary_accuracy: 0.7854 - loss: 0.7355 - val_auc: 0.8757 - val_binary_accuracy: 0.7649 - val_loss: 0.7428 - learning_rate: 2.5000e-04
Epoch 17/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 370ms/step - auc: 0.8738 - binary_accuracy: 0.7867 - loss: 0.7299 - val_auc: 0.8779 - val_binary_accuracy: 0.7862 - val_loss: 0.7403 - learning_rate: 2.5000e-04
Epoch 18/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 96s 363ms/step - auc: 0.8777 - binary_accuracy: 0.7915 - loss: 0.7286 - val_auc: 0.8785 - val_binary_accuracy: 0.7777 - val_loss: 0.7306 - learning_rate: 2.5000e-04
Epoch 19/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 143s 367ms/step - auc: 0.8765 - binary_accuracy: 0.7899 - loss: 0.7265 - val_auc: 0.8796 - val_binary_accuracy: 0.7947 - val_loss: 0.7286 - learning_rate: 2.5000e-04
Epoch 20/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 147s 386ms/step - auc: 0.8781 - binary_accuracy: 0.7910 - loss: 0.7238 - val_auc: 0.8808 - val_binary_accuracy: 0.7883 - val_loss: 0.7339 - learning_rate: 2.5000e-04
Epoch 21/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 140s 379ms/step - auc: 0.8801 - binary_accuracy: 0.7946 - loss: 0.7175 - val_auc: 0.8734 - val_binary_accuracy: 0.7991 - val_loss: 0.7335 - learning_rate: 2.5000e-04
Epoch 22/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 140s 371ms/step - auc: 0.8800 - binary_accuracy: 0.7909 - loss: 0.7146 - val_auc: 0.8747 - val_binary_accuracy: 0.7939 - val_loss: 0.7276 - learning_rate: 2.5000e-04
Epoch 23/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 97s 368ms/step - auc: 0.8823 - binary_accuracy: 0.7964 - loss: 0.7118 - val_auc: 0.8841 - val_binary_accuracy: 0.7890 - val_loss: 0.7233 - learning_rate: 2.5000e-04
Epoch 24/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 142s 366ms/step - auc: 0.8822 - binary_accuracy: 0.7952 - loss: 0.7069 - val_auc: 0.8855 - val_binary_accuracy: 0.8145 - val_loss: 0.7221 - learning_rate: 2.5000e-04
Epoch 25/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 141s 364ms/step - auc: 0.8837 - binary_accuracy: 0.7984 - loss: 0.7039 - val_auc: 0.8859 - val_binary_accuracy: 0.7683 - val_loss: 0.7352 - learning_rate: 2.5000e-04
Epoch 26/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 144s 372ms/step - auc: 0.8845 - binary_accuracy: 0.7959 - loss: 0.6983 - val_auc: 0.8787 - val_binary_accuracy: 0.8164 - val_loss: 0.7442 - learning_rate: 2.5000e-04
Epoch 27/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 146s 386ms/step - auc: 0.8849 - binary_accuracy: 0.7969 - loss: 0.6969 - val_auc: 0.8845 - val_binary_accuracy: 0.8243 - val_loss: 0.7172 - learning_rate: 2.5000e-04
Epoch 28/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 137s 367ms/step - auc: 0.8875 - binary_accuracy: 0.7985 - loss: 0.6910 - val_auc: 0.8766 - val_binary_accuracy: 0.8133 - val_loss: 0.7216 - learning_rate: 2.5000e-04
Epoch 29/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 368ms/step - auc: 0.8860 - binary_accuracy: 0.8012 - loss: 0.6929 - val_auc: 0.8880 - val_binary_accuracy: 0.7806 - val_loss: 0.7101 - learning_rate: 2.5000e-04
Epoch 30/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 142s 370ms/step - auc: 0.8884 - binary_accuracy: 0.8019 - loss: 0.6843 - val_auc: 0.8766 - val_binary_accuracy: 0.8042 - val_loss: 0.7329 - learning_rate: 2.5000e-04
Epoch 31/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 99s 371ms/step - auc: 0.8892 - binary_accuracy: 0.8008 - loss: 0.6787 - val_auc: 0.8842 - val_binary_accuracy: 0.7884 - val_loss: 0.7080 - learning_rate: 2.5000e-04
Epoch 32/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 104s 393ms/step - auc: 0.8903 - binary_accuracy: 0.8054 - loss: 0.6762 - val_auc: 0.8896 - val_binary_accuracy: 0.8250 - val_loss: 0.7051 - learning_rate: 2.5000e-04
Epoch 33/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 97s 368ms/step - auc: 0.8915 - binary_accuracy: 0.8051 - loss: 0.6705 - val_auc: 0.8715 - val_binary_accuracy: 0.7937 - val_loss: 0.7188 - learning_rate: 2.5000e-04
Epoch 34/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 99s 375ms/step - auc: 0.8934 - binary_accuracy: 0.8073 - loss: 0.6682 - val_auc: 0.8870 - val_binary_accuracy: 0.8046 - val_loss: 0.7068 - learning_rate: 2.5000e-04
Epoch 35/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 146s 389ms/step - auc: 0.8946 - binary_accuracy: 0.8092 - loss: 0.6636 - val_auc: 0.8931 - val_binary_accuracy: 0.7946 - val_loss: 0.6948 - learning_rate: 2.5000e-04
Epoch 36/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 371ms/step - auc: 0.8960 - binary_accuracy: 0.8089 - loss: 0.6566 - val_auc: 0.8878 - val_binary_accuracy: 0.8252 - val_loss: 0.7420 - learning_rate: 2.5000e-04
Epoch 37/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 97s 367ms/step - auc: 0.8967 - binary_accuracy: 0.8118 - loss: 0.6530 - val_auc: 0.8869 - val_binary_accuracy: 0.8209 - val_loss: 0.7139 - learning_rate: 2.5000e-04
Epoch 38/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 142s 367ms/step - auc: 0.8975 - binary_accuracy: 0.8110 - loss: 0.6512 - val_auc: 0.8833 - val_binary_accuracy: 0.8363 - val_loss: 0.7389 - learning_rate: 2.5000e-04
Epoch 39/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 370ms/step - auc: 0.9014 - binary_accuracy: 0.8169 - loss: 0.6366 - val_auc: 0.8982 - val_binary_accuracy: 0.8099 - val_loss: 0.6794 - learning_rate: 1.2500e-04
Epoch 40/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 368ms/step - auc: 0.9031 - binary_accuracy: 0.8193 - loss: 0.6309 - val_auc: 0.9002 - val_binary_accuracy: 0.8220 - val_loss: 0.6890 - learning_rate: 1.2500e-04
Epoch 41/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 98s 372ms/step - auc: 0.9033 - binary_accuracy: 0.8191 - loss: 0.6290 - val_auc: 0.8971 - val_binary_accuracy: 0.8137 - val_loss: 0.6844 - learning_rate: 1.2500e-04
Epoch 42/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 142s 369ms/step - auc: 0.9046 - binary_accuracy: 0.8206 - loss: 0.6232 - val_auc: 0.8978 - val_binary_accuracy: 0.8236 - val_loss: 0.6751 - learning_rate: 1.2500e-04
Epoch 43/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 140s 363ms/step - auc: 0.9043 - binary_accuracy: 0.8200 - loss: 0.6250 - val_auc: 0.8867 - val_binary_accuracy: 0.7840 - val_loss: 0.6938 - learning_rate: 1.2500e-04
Epoch 44/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 142s 363ms/step - auc: 0.9057 - binary_accuracy: 0.8228 - loss: 0.6181 - val_auc: 0.8957 - val_binary_accuracy: 0.8196 - val_loss: 0.6821 - learning_rate: 1.2500e-04
Epoch 45/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 99s 373ms/step - auc: 0.9071 - binary_accuracy: 0.8239 - loss: 0.6145 - val_auc: 0.8921 - val_binary_accuracy: 0.8110 - val_loss: 0.6849 - learning_rate: 1.2500e-04
Epoch 46/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 99s 372ms/step - auc: 0.9092 - binary_accuracy: 0.8235 - loss: 0.6063 - val_auc: 0.9008 - val_binary_accuracy: 0.8214 - val_loss: 0.6685 - learning_rate: 6.2500e-05
Epoch 47/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 141s 367ms/step - auc: 0.9097 - binary_accuracy: 0.8264 - loss: 0.6044 - val_auc: 0.9028 - val_binary_accuracy: 0.8294 - val_loss: 0.6723 - learning_rate: 6.2500e-05
Epoch 48/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 102s 387ms/step - auc: 0.9100 - binary_accuracy: 0.8277 - loss: 0.6017 - val_auc: 0.9008 - val_binary_accuracy: 0.8214 - val_loss: 0.6697 - learning_rate: 6.2500e-05
Epoch 49/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 97s 366ms/step - auc: 0.9111 - binary_accuracy: 0.8287 - loss: 0.5995 - val_auc: 0.9040 - val_binary_accuracy: 0.8241 - val_loss: 0.6733 - learning_rate: 6.2500e-05
Epoch 50/50
265/265 ━━━━━━━━━━━━━━━━━━━━ 102s 384ms/step - auc: 0.9116 - binary_accuracy: 0.8293 - loss: 0.5951 - val_auc: 0.9044 - val_binary_accuracy: 0.8265 - val_loss: 0.6658 - learning_rate: 3.1250e-05

In [15]:
y_prob = model.predict(X_test)

thresholds = np.arange(0.05, 0.91, 0.05)

rows = []

for t in thresholds:
    y_pred_t = (y_prob >= t).astype(int)

    rows.append({
        "threshold": round(float(t), 2),
        "micro_f1": f1_score(y_test, y_pred_t, average="micro", zero_division=0),
        "macro_f1": f1_score(y_test, y_pred_t, average="macro", zero_division=0),
        "samples_f1": f1_score(y_test, y_pred_t, average="samples", zero_division=0),
    })

import pandas as pd

threshold_df = pd.DataFrame(rows)

print("Best thresholds by macro F1:")
display(threshold_df.sort_values("macro_f1", ascending=False).head(10))

print("Best thresholds by micro F1:")
display(threshold_df.sort_values("micro_f1", ascending=False).head(10))

print("Best thresholds by samples F1:")
display(threshold_df.sort_values("samples_f1", ascending=False).head(10))

83/83 ━━━━━━━━━━━━━━━━━━━━ 15s 175ms/step
Best thresholds by macro F1:

    threshold  micro_f1  macro_f1  samples_f1
10       0.55  0.598720  0.325985    0.581988
9        0.50  0.580993  0.324171    0.570451
11       0.60  0.606709  0.321278    0.583536
12       0.65  0.609324  0.317224    0.578039
8        0.45  0.552824  0.316114    0.549312
7        0.40  0.525921  0.308009    0.525900
13       0.70  0.588971  0.291066    0.547313
6        0.35  0.500299  0.287752    0.501065
5        0.30  0.474911  0.273243    0.475271
4        0.25  0.448850  0.257311    0.449206

Best thresholds by micro F1:

    threshold  micro_f1  macro_f1  samples_f1
12       0.65  0.609324  0.317224    0.578039
11       0.60  0.606709  0.321278    0.583536
10       0.55  0.598720  0.325985    0.581988
13       0.70  0.588971  0.291066    0.547313
9        0.50  0.580993  0.324171    0.570451
8        0.45  0.552824  0.316114    0.549312
14       0.75  0.540653  0.256533    0.480132
7        0.40  0.525921  0.308009    0.525900
6        0.35  0.500299  0.287752    0.501065
5        0.30  0.474911  0.273243    0.475271

Best thresholds by samples F1:

    threshold  micro_f1  macro_f1  samples_f1
11       0.60  0.606709  0.321278    0.583536
10       0.55  0.598720  0.325985    0.581988
12       0.65  0.609324  0.317224    0.578039
9        0.50  0.580993  0.324171    0.570451
8        0.45  0.552824  0.316114    0.549312
13       0.70  0.588971  0.291066    0.547313
7        0.40  0.525921  0.308009    0.525900
6        0.35  0.500299  0.287752    0.501065
14       0.75  0.540653  0.256533    0.480132
5        0.30  0.474911  0.273243    0.475271

In [16]:
BEST_THRESHOLD = 0.55

y_pred = (y_prob >= BEST_THRESHOLD).astype(int)

micro_f1 = f1_score(y_test, y_pred, average="micro", zero_division=0)
macro_f1 = f1_score(y_test, y_pred, average="macro", zero_division=0)
samples_f1 = f1_score(y_test, y_pred, average="samples", zero_division=0)

print("Final Improved CNN Evaluation")
print("Threshold:", BEST_THRESHOLD)
print("Micro F1:", micro_f1)
print("Macro F1:", macro_f1)
print("Samples F1:", samples_f1)

print(classification_report(
    y_test,
    y_pred,
    target_names=LABEL_NAMES,
    zero_division=0
))

Final Improved CNN Evaluation
Threshold: 0.55
Micro F1: 0.59872
Macro F1: 0.325985132030552
Samples F1: 0.581987790432136
                 precision    recall  f1-score   support

          ester       0.37      0.69      0.48       412
carboxylic_acid       0.12      0.77      0.20       132
         alkane       0.82      0.98      0.89      2121
         alkene       0.27      0.42      0.33       375
        alcohol       0.44      0.67      0.53       667
          arene       0.81      0.77      0.79      1670
          amine       0.51      0.55      0.53       798
         ketone       0.24      0.51      0.32       260
          ether       0.49      0.56      0.52       749
          imine       0.57      0.49      0.52        35
    sulfonamide       0.44      0.20      0.27        41
    acyl_halide       0.00      0.00      0.00        11
      phosphate       0.12      0.39      0.18        49
       aldehyde       0.30      0.50      0.38        56
          nitro       0.15      0.60      0.24       158
        enamine       0.00      0.00      0.00         5
            azo       0.00      0.00      0.00        27
  sulfonic_acid       0.00      0.00      0.00        20
          amide       0.22      0.63      0.33       148
       peroxide       0.00      0.00      0.00         3

      micro avg       0.51      0.73      0.60      7737
      macro avg       0.29      0.44      0.33      7737
   weighted avg       0.59      0.73      0.64      7737
    samples avg       0.56      0.71      0.58      7737

In [17]:
model.save("weighted_ftir_cnn_threshold_055.keras")

In [18]:
import pandas as pd

cnn_final_summary = pd.DataFrame([{
    "model": "Weighted 1D CNN",
    "threshold": BEST_THRESHOLD,
    "micro_f1": micro_f1,
    "macro_f1": macro_f1,
    "samples_f1": samples_f1,
}])

cnn_final_summary.to_csv("weighted_cnn_summary.csv", index=False)
cnn_final_summary

             model  threshold  micro_f1  macro_f1  samples_f1
0  Weighted 1D CNN       0.55   0.59872  0.325985    0.581988

In [19]:
from google.colab import files

files.download("weighted_ftir_cnn_threshold_055.keras")
files.download("weighted_cnn_summary.csv")